# Project-related configuration
cs35:
  name: CS35
  version: 1.0.1
  copyrightYear: 2024
  profile: C:/cs35/uploadPath
  # Obtain the ip address switch
  addressEnabled: false
  # Verification Code Type math Numeric calculation char Character verification
  captchaType: math

server:
  port: 10100
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

logging:
  level:
    com.cs35: debug
    org.springframework: warn

user:
  password:
    maxRetryCount: 5
    lockTime: 10

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      # Individual file size
      max-file-size: 10MB
      # Set the total file size to be uploaded
      max-request-size: 20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  # Token validity period (default: 30 minutes)
  expireTime: 30

#mybatis:
#  typeAliasesPackage: com.cs35.**.domain
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.cs35.**.domain,com.cs35.**.entity
  global-config:
    #
    banner: false
    db-config:
      #
      id-type: auto

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: true
  pathMapping: /dev-api

xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*,/tool/*
